name: cis583_env
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.25.0
  - ipython=8.20.0
  - joblib=1.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - matplotlib=3.8.0
  - nltk=3.8.1
  - numpy=1.26.4
  - pandas=2.1.1
  - pillow=10.2.0
  - pip>=23.3.1
  - python=3.10.13
  - regex=2023.10.3
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - spacy=3.7.2
  - pip:
      - seaborn==0.13.2
      - tensorboard==2.14.1
      - tensorflow==2.14.0